### Clean the data

In [1]:
from clean_data import *

wavs_train, labels_train = raw_to_list('..\\raw_data\\train')
wavs_test, labels_test = raw_to_list('..\\raw_data\\test')

### Featurize

In [2]:
from pyaudio_features import *

In [3]:
train = pyaudio_featurize(wavs_train)
test = pyaudio_featurize(wavs_test)

In [4]:
train.head()

zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0  0.107035     0.056063             2.971335                0.220453   
1  0.097999     0.051491             2.915951                0.215335   
2  0.117095     0.041029             3.052197                0.226457   
3  0.098396     0.054808             2.913821                0.216494   
4  0.100803     0.054753             3.001715                0.214912   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.238855               0.787558            0.003378   
1              0.239961               0.656975            0.003868   
2              0.232912               0.948379            0.002733   
3              0.241115               0.650022            0.004039   
4              0.231083               0.761204            0.003312   

   spectral_rolloff_mean  mfcc_1_mean  mfcc_2_mean  ...  delta chroma_4_std  \
0               0.137665   -22.409211     1.887336  ...            0.010627   
1               0.104695   -22.503605     2.080040  ...            0.015253   
2               0.180105   -22.402818     1.747582  ...            0.012116   
3               0.127446   -23.640921     2.092937  ...            0.009302   
4               0.136635   -22.434949     1.914857  ...            0.013266   

   delta chroma_5_std  delta chroma_6_std  delta chroma_7_std  \
0            0.017674            0.014972            0.042528   
1            0.025090            0.009762            0.065102   
2            0.020286            0.008671            0.058385   
3            0.019578            0.004110            0.042374   
4            0.025375            0.005584            0.065045   

   delta chroma_8_std  delta chroma_9_std  delta chroma_10_std  \
0            0.001925            0.003215             0.013251   
1            0.001856            0.005543             0.016592   
2            0.002686            0.005608             0.008269   
3            0.002510            0.003732             0.019380   
4            0.002238            0.005144             0.021406   

   delta chroma_11_std  delta chroma_12_std  delta chroma_std_std  
0             0.025270             0.005796              0.010108  
1             0.029970             0.002841              0.012824  
2             0.025247             0.003040              0.013087  
3             0.027746             0.001873              0.010099  
4             0.026089             0.003593              0.013791  

[5 rows x 136 columns]

### Scale data

In [7]:
train, test = scaling(train,test)

### Merge labels

In [8]:
merge_labels(train,labels_train)
merge_labels(test,labels_test)

In [9]:
train.head()

zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0 -0.521908     0.408802            -1.359347               -0.736467   
1 -0.892723     0.159370            -2.069101               -0.974816   
2 -0.109051    -0.411510            -0.323065               -0.456878   
3 -0.876437     0.340319            -2.096405               -0.920827   
4 -0.777662     0.337318            -0.970009               -0.994520   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.268848              -0.908276            0.342074   
1              0.345817              -1.351765            0.971089   
2             -0.144778              -0.362088           -0.485131   
3              0.426133              -1.375379            1.191010   
4             -0.272082              -0.997781            0.257410   

   spectral_rolloff_mean  mfcc_1_mean  mfcc_2_mean  ...  delta chroma_4_std  \
0              -1.016643     0.373994     1.004177  ...            0.248236   
1              -1.532693     0.244131     1.556954  ...            1.267554   
2              -0.352372     0.382789     0.603286  ...            0.576240   
3              -1.176596    -1.320530     1.593949  ...           -0.043830   
4              -1.032771     0.338585     1.083122  ...            0.829685   

   delta chroma_5_std  delta chroma_6_std  delta chroma_7_std  \
0           -0.431496            3.475260           -0.633558   
1            0.874598            1.431606            0.617133   
2            0.028579            1.003436            0.244978   
3           -0.096069           -0.785812           -0.642089   
4            0.924826           -0.207522            0.613954   

   delta chroma_8_std  delta chroma_9_std  delta chroma_10_std  \
0            0.098560           -0.291840            -0.125135   
1            0.040971            1.005318             0.607970   
2            0.732326            1.041190            -1.218329   
3            0.586032           -0.003975             1.219896   
4            0.359247            0.782846             1.664331   

   delta chroma_11_std  delta chroma_12_std  delta chroma_std_std  
0            -0.721808             2.463158             -0.545366  
1            -0.245224             0.160476              0.313900  
2            -0.724144             0.316164              0.397308  
3            -0.470740            -0.593611             -0.548138  
4            -0.638765             0.746623              0.619854  

[5 rows x 137 columns]

In [10]:
test.head()

zcr_mean  energy_mean  energy_entropy_mean  spectral_centroid_mean  \
0 -1.441757     0.380871            -0.841928               -1.128917   
1 -1.102280    -0.227291             0.019206               -1.207525   
2 -1.912468     0.154554            -0.631645               -1.762299   
3 -1.978652     0.011107            -0.227988               -1.583081   
4 -1.086803     0.012628            -0.204669               -1.265583   

   spectral_spread_mean  spectral_entropy_mean  spectral_flux_mean  \
0              0.285666              -1.316558            0.820852   
1             -0.819952              -0.636992            0.353192   
2             -0.520817              -1.593449            1.550500   
3              0.520420              -1.818393            1.106436   
4             -0.507222              -0.845815            0.217595   

   spectral_rolloff_mean  mfcc_1_mean  mfcc_2_mean  ...  delta chroma_4_std  \
0              -1.708952     0.162678     0.945547  ...            0.046404   
1              -0.874478     0.170150     0.354886  ...           -0.013183   
2              -1.980639    -0.118832     1.037414  ...            1.138973   
3              -1.766301    -1.081780     2.265629  ...           -0.151105   
4              -1.007925     0.667095     0.926392  ...            0.993716   

   delta chroma_5_std  delta chroma_6_std  delta chroma_7_std  \
0            1.779936           -0.701699            0.250112   
1            2.447427           -0.001309           -0.821147   
2            0.672429            1.034335            0.101946   
3           -1.126784            2.380380           -0.399282   
4            0.503980            1.567277            0.097476   

   delta chroma_8_std  delta chroma_9_std  delta chroma_10_std  \
0           -0.047675            0.035181             0.513071   
1            1.036855           -0.171834            -0.438956   
2           -0.792703           -0.075051             0.987204   
3           -0.868867           -1.258386            -1.064313   
4           -0.020590            0.269703             0.693858   

   delta chroma_11_std  delta chroma_12_std  delta chroma_std_std  
0            -0.896671            -1.191891              0.188773  
1            -0.825538            -0.190682             -0.438365  
2            -0.615343            -0.584320             -0.194847  
3            -1.295228             2.111874             -0.108914  
4            -0.702604             0.471929              0.264869  

[5 rows x 137 columns]

### Save Data to clean_data folder

In [16]:
train.to_csv('../clean_data/train/train.csv',index=False)
test.to_csv('../clean_data/test/test.csv',index=False)

### Load

In [19]:
train = pd.read_csv('../clean_data/train/train.csv')
test = pd.read_csv('../clean_data/test/test.csv')

In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold

In [34]:
neigh = KNeighborsClassifier(n_neighbors=20)
neigh.fit(train.drop(['Band'],axis=1),train['Band'])
preds = neigh.predict(test.drop(['Band'],axis=1))
print(accuracy_score(test['Band'],preds))
print(confusion_matrix(test['Band'],preds))

0.5
[[ 4  2  4]
 [ 0 10  0]
 [ 3  6  1]]


In [45]:
rf = RandomForestClassifier(n_estimators=10)
rf.fit(train.drop(['Band'],axis=1),train['Band'])
preds = rf.predict(test.drop(['Band'],axis=1))
print(accuracy_score(test['Band'],preds))
print(confusion_matrix(test['Band'],preds))

0.5333333333333333
[[ 4  1  5]
 [ 0 10  0]
 [ 1  7  2]]


In [22]:
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import LeavePOut

In [38]:
lpo = StratifiedShuffleSplit(n_splits=20)

In [62]:
# enumerate splits
# create model
model = RandomForestClassifier(n_estimators=25)
# evaluate model
scores = cross_val_score(model, train.drop(['Band'],axis=1), train['Band'], scoring='accuracy', cv=lpo)
# report performance
print('Accuracy: %.3f (%.3f)' % (np.mean(scores), np.std(scores)))

Accuracy: 0.783 (0.108)


In [63]:
model.fit(train.drop(['Band'],axis=1),train['Band'])
preds = model.predict(test.drop(['Band'],axis=1))
print(accuracy_score(test['Band'],preds))
print(confusion_matrix(test['Band'],preds))

0.6
[[7 1 2]
 [1 9 0]
 [5 3 2]]


In [8]:
model = RandomForestClassifier(random_state=1,n_estimators=8)
model.fit(tr.drop(['Band'],axis=1),tr['Band'])

RandomForestClassifier(n_estimators=8, random_state=1)

In [9]:
preds = model.predict(test.drop(['Band'],axis=1))
preds_train = model.predict(tr.drop(['Band'],axis=1))

In [10]:
print(accuracy_score(test['Band'],preds))
print(confusion_matrix(test['Band'],preds))

0.6
[[6 2 2]
 [1 9 0]
 [6 1 3]]
